### ISSUE TITLE
[BUG-3] Display Images on Diagram Explanation

### ISSUE THREAD

**Issue by lucas-mrq** [NiskuT/Civilization#36]
Images are not dispayed on the website, even with only the name of the images.

**Comment by jard-111** [comment]
I can't find the page on which the images are missing. do you have a link?

**Comment by lucas-mrq** [comment]
They are in docs/diagram-explanations.md [here](https://github.com/NiskuT/Civilization/blob/main/docs/diagram-explanation.md)

**Comment by jard-111** [comment]
The github action "mattnotmitt/doxygen-action@v1.1.0" does not support dia diagrams. 
Indeed, doxygen needs dia to create diagrams (cf. [here](<https://github.com/NiskuT/Civilization/actions/runs/3307260942/jobs/5458757710#step:4:134>))
The solution can be:
- Use png images generated from the dia file (require manual changes when the dia is modified)
- Create our own action for the doxygen documentation.
